CREATE DATABASE moviesdatabase;
DROP DATABASE IF EXISTS;

\c moviesdatabase

DROP TABLE IF EXISTS movies;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS ratings;
DROP TABLE IF EXISTS comments;

CREATE TABLE movies(
id SERIAL PRIMARY KEY,
title VARCHAR NOT NULL UNIQUE,
genre_id INT NOT NULL,
img_url VARCHAR NOT NULL
);

CREATE TABLE genres(
  id SERIAL PRIMARY KEY,
  name VARCHAR NOT NULL
);
